name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Lua
      uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: '5.1'
    
    - name: Install dependencies
      run: |
        luarocks install busted
        luarocks install luassert
        luarocks install lua-cjson
    
    - name: Run tests
      run: |
        busted tests/
    
    - name: Check Lua syntax
      run: |
        find lua/ -name "*.lua" -exec luac -p {} \;
    
    - name: Check for common issues
      run: |
        # Check for TODO comments that might indicate incomplete features
        if grep -r "TODO" lua/; then
          echo "Warning: Found TODO comments in code"
        fi
        
        # Check for FIXME comments
        if grep -r "FIXME" lua/; then
          echo "Warning: Found FIXME comments in code"
        fi 